from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import json,subprocess,statistics
ROOT=Path(__file__).resolve().parents[2];WORK=ROOT/'working/office-cinema';OUT=WORK/'review';OUT.mkdir(exist_ok=True)
font=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',20)
labels=['01 · Computador e mesa','02 · Recuo da estação','03 · Deslocamento lateral','04 · Escritório e janela'];frames=[1,41,81,121]
sheet=Image.new('RGB',(1280,800),'#f0ede6');d=ImageDraw.Draw(sheet);sizes=[]
for i,f in enumerate(frames):
 src=WORK/'previews'/f'frame-{f:04d}.png'
 if not src.exists():continue
 im=Image.open(src).convert('RGB');im.save(OUT/f'preview-{i+1}.webp',quality=82,method=6);sizes.append((OUT/f'preview-{i+1}.webp').stat().st_size)
 thumb=im.resize((640,360),Image.Resampling.LANCZOS);x=i%2*640;y=i//2*400;sheet.paste(thumb,(x,y));d.text((x+16,y+370),labels[i],font=font,fill='#242731')
sheet.save(OUT/'four-previews.jpg',quality=93)
mobile=WORK/'mobile/frame-0001.png'
if mobile.exists():Image.open(mobile).convert('RGB').save(OUT/'mobile-preview.webp',quality=82,method=6)
# Real, consecutive rendered frames. No optical-flow/generated intermediate frames.
motion=WORK/'motion'
if (motion/'frame-0021.png').exists() and (motion/'frame-0032.png').exists():
 import imageio_ffmpeg
 subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(),'-y','-framerate','12','-start_number','21','-i',str(motion/'frame-%04d.png'),'-frames:v','12','-c:v','libx264','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',str(OUT/'motion-sample.mp4')],check=True,capture_output=True)
 ims=[Image.open(motion/f'frame-{f:04d}.png').convert('RGB') for f in range(21,33)]
 ims[0].save(OUT/'motion-sample.gif',save_all=True,append_images=ims[1:],duration=83,loop=0)
# Estimate from actual production-resolution preview timings, not a theoretical GPU rate.
timings=json.loads((WORK/'previews/timings.json').read_text());seconds=[f['seconds'] for f in timings['frames']]
est={'preview_seconds_per_frame':seconds,'mean_seconds':statistics.mean(seconds),'webp_bytes_per_frame':sizes,'mean_webp_bytes':statistics.mean(sizes),'proposed_final':{'frames':121,'desktop_resolution':[1280,720],'samples':32,'estimated_render_hours_range':[statistics.mean(seconds)*121*(1280*720)/(timings["width"]*timings["height"])/3600*1.15,statistics.mean(seconds)*121*(1280*720)/(timings["width"]*timings["height"])/3600*1.8],'estimated_desktop_mb_range':[statistics.mean(sizes)*121*3/1e6,statistics.mean(sizes)*121*4.5/1e6],'note':'Extrapolation from 640x360 previews. 1280x720 requires overlapping tile renders because 960x540 full-frame denoise exceeded available memory. Tile overhead included as an allowance, not benchmarked. Portrait sequence is a separate budget.'}}
(OUT/'estimate.json').write_text(json.dumps(est,indent=2))
html='''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AVLS — prévias do escritório</title><style>
*{box-sizing:border-box}body{margin:0;background:#f1eee7;color:#242731;font:16px/1.6 Arial,sans-serif}main{max-width:1320px;margin:auto;padding:32px 24px}h1{font-size:clamp(28px,4vw,48px);line-height:1.1}p{max-width:800px}a{color:#514478}figure{margin:0;background:#fff;border:1px solid #cfc9bc;border-radius:14px;overflow:hidden}img,video{display:block;width:100%}figcaption{padding:12px 18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}video{max-width:720px}.phone{max-width:360px;position:relative;border:8px solid #262a32;border-radius:28px;overflow:hidden}.desktop-composition{position:relative;margin:24px 0;overflow:hidden;border-radius:14px}.desktop-copy{position:absolute;left:3%;top:12%;width:37%;padding:3%;background:#f7f4ec;color:#1d222c;border-radius:14px}.desktop-copy h2{font-size:clamp(18px,3vw,40px);line-height:1.05;margin:0 0 14px}.desktop-copy p{font-size:clamp(10px,1.1vw,15px);line-height:1.4;margin:0}.desktop-copy span{display:inline-block;margin-top:16px;background:#222832;color:white;padding:10px 16px;border-radius:30px;font-size:12px}.phone .copy{position:absolute;top:22px;left:14px;right:14px;padding:18px;background:#f7f4ec;color:#1d222c;border-radius:14px}.copy h2{font-size:25px;line-height:1.1;margin:0 0 10px}.copy p{font-size:12px;line-height:1.4;margin:0}.copy span{display:inline-block;margin-top:12px;background:#222832;color:white;padding:9px 15px;border-radius:30px;font-size:12px}footer{margin-top:40px;border-top:1px solid #ccc6bb;padding-top:20px;font-size:12px}@media(max-width:700px){.grid{grid-template-columns:1fr}.desktop-copy{position:static;width:auto;padding:20px;border-radius:0}.desktop-copy h2{font-size:28px}.desktop-copy p{font-size:14px}}
</style><main><h1>AVLS / Escritório cinematográfico</h1><p>Prévias em Cycles para aprovação visual. Esta página é um material de revisão separado: o site atual ainda não foi alterado. As quatro imagens de avaliação têm 640 × 360 px e 32 amostras; o vertical tem 360 × 640 px. A amostra usa 12 quadros consecutivos reais em 480 × 270 px, durante 1 segundo.</p><div class="grid">'''
for i,label in enumerate(labels):html+=f'<figure><a href="preview-{i+1}.webp"><img src="preview-{i+1}.webp" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
html+='</div><h2>Área de leitura no desktop</h2><div class="desktop-composition"><img src="preview-1.webp" alt="Computador AVLS com área de texto à esquerda"><div class="desktop-copy"><h2>Do ideal<br>ao extraordinário.</h2><p>Estratégia que gera resultados. Criamos sites, marcas e experiências digitais para levar seu negócio mais longe.</p><span>Vamos criar juntos ↗</span></div></div><p>Estudo de composição com texto HTML e superfície local opaca. A imagem permanece sem uma camada branca sobre o cenário inteiro.</p><h2>Amostra curta de movimento</h2><video src="motion-sample.mp4" controls loop preload="metadata" poster="preview-2.webp"></video>'
if mobile.exists():html+='''<h2>Composição para celular</h2><p>Enquadramento vertical renderizado separadamente. O bloco HTML ilustra a área reservada para título e CTA; não é uma implementação no site.</p><div class="phone"><img src="mobile-preview.webp" alt="Escritório em enquadramento vertical"><div class="copy"><h2>Do ideal ao extraordinário.</h2><p>Estratégia que gera resultados. Criamos sites, marcas e experiências digitais para levar seu negócio mais longe.</p><span>Vamos criar juntos ↗</span></div></div>'''
proposal=est['proposed_final'];hours=proposal['estimated_render_hours_range'];mb=proposal['estimated_desktop_mb_range']
html+=f"<h2>Estimativa para a sequência</h2><p>121 quadros em 1280 × 720: aproximadamente {hours[0]:.1f}–{hours[1]:.1f} horas e {mb[0]:.1f}–{mb[1]:.1f} MB em WebP. Estimativa extrapolada; a resolução final exigirá render em blocos por causa do limite de memória. O custo dos blocos ainda não foi medido. Uma sequência vertical tem custo adicional.</p>"
html+='''<footer>Modelo 3D “<a href="https://skfb.ly/oDPCS">Modern Office</a>” por <a href="https://skfb.ly/oDPCS">dylanheyes</a> — <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Adaptado para AVLS.<br>Modificações: materiais e iluminação; estação reposicionada; notebook com logo real; café; arte do quadro; vegetação externa derivada da planta original; trajetória e enquadramentos.</footer></main></html>'''
(OUT/'index.html').write_text(html,encoding='utf8');print(json.dumps(est,indent=2))
